version: "2"

services:
  app:
    build: "."
    networks:
      - "default"
    volumes:
      - "./:/data/app"
    user: "www-data"
    command: "sleep 999999"
networks:
  default:
    driver: "bridge"